### ISSUE TITLE
generating idea project

### ISSUE THREAD

**Issue by Parabellum1905y** [xitrum-framework/xitrum-new#12]
Using this tutorial :http://xitrum-framework.github.io/guide/3.17/html/ru/tutorial.html i get this error:
`
Not a valid key: gen-idea[error] gen-idea[error]`

**Comment by ngocdaothanh** [comment]
Thanks for reporting.
I'll modify the instruction.

That was for old version of IntelliJ, several years ago.
Now in 2016, you simply need to install Scala plugin for IntelliJ, then open the project.
