### ISSUE TITLE
Static files like favicon.ico or whale.png get a 404

### ISSUE THREAD

**Issue by zoosky** [xitrum-framework/xitrum-new#7]
I test on a Mac.

    <meta name="csrf-token" content="a72528d3-2a3b-45b3-8590-58ae8a530069"/>

    <link rel="shortcut icon" href="/favicon.ico?312726893271885356"/>

      <p>
        Whale  Image
        <img src="/whale.png?-3714092246596795823"/>
      </p>
      <p>
  

localhost/:22 GET http://localhost:8000/whale.png?-3714092246596795823 404 (Not Found)
localhost/:10 GET http://localhost:8000/app.css?5709128349347965299

**Comment by ngocdaothanh** [comment]
I'm also using Mac. I tried the project xitrum-new and didn't see that problem.

Have you strangely modified somewhere in the project?
In config/xitrum.conf, there's this line:
https://github.com/xitrum-framework/xitrum-new/blob/master/config/xitrum.conf#L113
It tells the Xitrum web server to serve static files with the configured file extension.

**Comment by zoosky** [comment]
OK.  I did a fresh git clone on the project. I have  

     java -version
     java version "1.8.0_25"
     Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
     Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

The logs show that whale and favicon are not found.

[info] Set current project to xitrum-new (in build file:/Users  ... /xitrum/xitrum-new/)
[info] Updating {file:/Users/a ... /xitrum/xitrum-new/}xitrum-new...
[info] Resolving org.scala-lang#scala-reflect;2.11.0 ...
[info] Done updating.
[info] Compiling Templates in Template Directory: /Users/   ... /xitrum/xitrum-new/src/main/scalate
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[info] Compiling 8 Scala sources to /Users/ ... xitrum/xitrum-new/target/scala-2.11/classes...
[info] Running quickstart.Boot 
[INFO] Slf4jLogger started
[INFO] Load tmp/routes.cache or recollect routes...
[INFO] Glokka actor registry "xitrum.sockjs.SockJsAction$" starts in local mode
[INFO] Glokka actor registry "metrics" starts in local mode
[INFO] Normal routes:
GET  /  quickstart.action.SiteIndex
[INFO] Error routes:
404  quickstart.action.NotFoundError
500  quickstart.action.ServerError
[INFO] Xitrum routes:
GET  /xitrum/xitrum.js       xitrum.js
GET  /xitrum/metrics/viewer  xitrum.metrics.XitrumMetricsViewer
[INFO] Xitrum SockJS routes:
/xitrum/metrics/channel  xitrum.metrics.XitrumMetricsChannel  websocket: true, cookie_needed: false
[INFO] HTTP server started on port 8000
[INFO] HTTPS server started on port 4430
[INFO] Xitrum 3.22 started in development mode
[WARN] *** For security, change secureKey in config/xitrum.conf to your own! ***
[INFO] 0:0:0:0:0:0:0:1 GET / -> quickstart.action.SiteIndex -> 200, 4431 [ms]
[INFO] 0:0:0:0:0:0:0:1 GET / -> quickstart.action.SiteIndex -> 200, 4391 [ms]
[INFO] 0:0:0:0:0:0:0:1 GET /app.css?-6787575015738558728 -> quickstart.action.NotFoundError, queryParams: {-6787575015738558728: } -> 404, 169 [ms]
[INFO] 0:0:0:0:0:0:0:1 GET /whale.png?4547606110448102217 -> quickstart.action.NotFoundError, queryParams: {4547606110448102217: } -> 404, 219 [ms]
[INFO] 0:0:0:0:0:0:0:1 GET /favicon.ico?-8358526266766970322 -> quickstart.action.NotFoundError, queryParams: {-8358526266766970322: } -> 404, 7 [ms]
[INFO] 0:0:0:0:0:0:0:1 GET /app.css?-6787575015738558728 -> quickstart.action.NotFoundError, queryParams: {-6787575015738558728: } -> 404, 10 [ms]
[INFO] 0:0:0:0:0:0:0:1 GET /webjars/bootstrap/3.3.2/css/bootstrap.css.map -> 200 (JAR resource)
[INFO] 0:0:0:0:0:0:0:1 GET / -> quickstart.action.SiteIndex -> 200, 28 [ms]
[INFO] 0:0:0:0:0:0:0:1 GET /webjars/xitrum/3.22/xitrum.css?WeZg0rcDACGbqN_6cAf2jw -> 200 (JAR resource)
[INFO] 0:0:0:0:0:0:0:1 GET /webjars/bootstrap/3.3.2/css/bootstrap.css?vmZbufD3_In1Fa24KPoKmw -> 200 (JAR resource)
[INFO] 0:0:0:0:0:0:0:1 GET /xitrum/xitrum.js?KJPEdjYavfZXUD_hg_ycxQ -> xitrum.js, queryParams: {KJPEdjYavfZXUD_hg_ycxQ: } -> 200, 13 [ms]
[INFO] 0:0:0:0:0:0:0:1 GET /webjars/jquery-validation/1.13.1/jquery.validate.js?nsRlEgC02PH6To2p2uG4Bg -> 200 (JAR resource)
[INFO] 0:0:0:0:0:0:0:1 GET /app.css?5872985981214523372 -> quickstart.action.NotFoundError, queryParams: {5872985981214523372: } -> 404, 7 [ms]
[INFO] 0:0:0:0:0:0:0:1 GET /webjars/jquery-validation/1.13.1/additional-methods.js?ZLoYagRvekDQQm78EMa_dQ -> 200 (JAR resource)
[INFO] 0:0:0:0:0:0:0:1 GET /webjars/sockjs-client/0.3.4/sockjs.js?G6ezG627D2WKnJ3F55SoNQ -> 200 (JAR resource)
[INFO] 0:0:0:0:0:0:0:1 GET /whale.png?1999222093966925982 -> quickstart.action.NotFoundError, queryParams: {1999222093966925982: } -> 404, 6 [ms]
[INFO] 0:0:0:0:0:0:0:1 GET /webjars/jquery/2.1.3/jquery.js?zyb48Mywa-cektjbD7ZKtQ -> 200 (JAR resource)
[INFO] 0:0:0:0:0:0:0:1 GET /favicon.ico?-8344956078364779082 -> quickstart.action.NotFoundError, queryParams: {-8344956078364779082: } -> 404, 5 [ms]

**Comment by ngocdaothanh** [comment]
Did you run with SBT, or via IDEs like Eclipse or IntelliJ?
If you didn't run with SBT, please give it a try (`sbt run`).

> Compiling 8 Scala sources to /Users/ ... xitrum/xitrum-new/target/scala-2.11/classes...

Can you give the full path?
May be your path contains special character and Xitrum can't understand.

If that's not the case, can you also try other Xitrum example projects?
https://github.com/xitrum-framework/xitrum-demos
https://github.com/xitrum-framework/xitrum-placeholder
https://github.com/xitrum-framework/xitrum-tictactoe

Also, please try removing Xitrum .jar files to force SBT to download them again:
```
find ~/.ivy2 -name *xitrum* -exec rm -rf {} \;
```

**Comment by ngocdaothanh** [comment]
Hi, do you have any progress on this problem?

**Comment by ngocdaothanh** [comment]
Close because not producible and there's no update.
